version: '3.7'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ".:/usr/share/nginx/html"
    environment:
      NGINX_HOST: foobar.com
      NGINX_PORT: 80
